### ISSUE TITLE
HTML rendering issue with valid RAML for security schemes.

### ISSUE THREAD

**Issue by ageoghegan** [blzjns/vscode-raml#19]
RAML snippet...
```
securitySchemes:
  basic:
    description: This API supports Basic Authentication.
    type: Basic Authentication
securedBy: [basic]
```

Error response when rendering HTML:
Error: Command failed: raml2html --template c:\Users\ageoghegan\.vscode\extensions\blzjns.vscode-raml-3.0.1\raml2html_template/dark.nunjucks d:\Repos\8West\provider-master-data-api\raml\api.raml
Template render error: (c:\Users\ageoghegan\.vscode\extensions\blzjns.vscode-raml-3.0.1\raml2html_template\dark.nunjucks)
  Template render error: (c:\Users\ageoghegan\.vscode\extensions\blzjns.vscode-raml-3.0.1\raml2html_template\resource.nunjucks) [Line 71, Column 62]
  Error: Unable to call `renderSecuredBy`, which is undefined or falsey
